# Try not to use all parameters at the same time to avoid undefined behaviors
# Here LPModel can only be one of 'RandomForest', 'SVM' and 'NB'
LPModel: 'RandomForest'
dataPath: './data/BoolTrainData/'
k: 2
m: 6
# Below is RandomForest Parameters

# Below is SVM parameters

# Below is NB parameters
